# Generated by Django 5.0.14 on 2026-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
