# Generated by Django 5.0.14 on 2026-05-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0002_alter_gene_gene_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
